-- Crear la base de datos TrioTech en MySQL
CREATE DATABASE TrioTech;

-- Usar la base de datos
USE TrioTech;

-- Tabla CLIENTE con ID_CLIENTE autoincrementable
CREATE TABLE CLIENTE
(
    ID_CLIENTE INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO_PATERNO VARCHAR(20) NOT NULL,
    APELLIDO_MATERNO VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL
);

-- Tabla EQUIPO con ID_EQUIPO autoincrementable
CREATE TABLE EQUIPO
(
    ID_EQUIPO INT AUTO_INCREMENT PRIMARY KEY,
    ID_CLIENTE INT NOT NULL,
    PROCESADOR VARCHAR(20) NOT NULL,
    GRAFICA VARCHAR(20) NOT NULL,
    DISCO_DURO VARCHAR(20) NOT NULL,
    MEMORIA_RAM VARCHAR(20) NOT NULL,
    REPARADO TINYINT NOT NULL,
    FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE)
);

-- Tabla TECNICO con ID_TECNICO autoincrementable
CREATE TABLE TECNICO
(
    ID_TECNICO INT AUTO_INCREMENT PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO_PATERNO VARCHAR(20) NOT NULL,
    APELLIDO_MATERNO VARCHAR(20) NOT NULL,
    TELEFONO VARCHAR(12) NOT NULL
);

-- Tabla MANTENIMIENTO con ID_MANTENIMIENTO autoincrementable
CREATE TABLE MANTENIMIENTO 
(
    ID_MANTENIMIENTO INT AUTO_INCREMENT PRIMARY KEY,
    ID_EQUIPO INT NOT NULL,
    ID_TECNICO INT NOT NULL,
    DESCRIPCION VARCHAR(50) NOT NULL,
    FECHA_INGRESO DATE NOT NULL,
    FECHA_SALIDA DATE,
    TOTAL DECIMAL(12, 2),
    FOREIGN KEY (ID_EQUIPO) REFERENCES EQUIPO(ID_EQUIPO),
    FOREIGN KEY (ID_TECNICO) REFERENCES TECNICO(ID_TECNICO)
);
